/* Generated by Yosys 0.61+21 (git sha1 967b47d98, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "original.v:1.1-5.10" *)
module top(A, B, C, F);
  (* src = "original.v:1.18-1.19" *)
  input A;
  wire A;
  (* src = "original.v:1.21-1.22" *)
  input B;
  wire B;
  (* src = "original.v:1.24-1.25" *)
  input C;
  wire C;
  (* src = "original.v:1.34-1.35" *)
  output F;
  wire F;
  (* src = "original.v:4.17-4.22" *)
  wire _0_;
  (* src = "original.v:4.27-4.36" *)
  wire _1_;
  assign _0_ = A & (* src = "original.v:4.17-4.22" *) B;
  assign _1_ = _0_ & (* src = "original.v:4.27-4.36" *) C;
  assign F = _0_ | (* src = "original.v:4.16-4.37" *) _1_;
endmodule
